apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: syncshield-safefail
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/your-org/kiki_agent.git
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: syncshield-safefail
  namespace: syncshield
spec:
  interval: 5m
  releaseName: syncshield-safefail
  chart:
    spec:
      chart: ./deploy/charts/syncshield-safefail
      sourceRef:
        kind: GitRepository
        name: syncshield-safefail
        namespace: flux-system
      interval: 1m
  values:
    logShipping:
      enabled: true
      backend: elasticsearch
      elasticsearchUrl: http://elasticsearch:9200
