apiVersion: v1
kind: Service
metadata:
  name: "{{ include \"kiki-agent.fullname\" . }}-syncbrain"
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: syncbrain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include \"kiki-agent.fullname\" . }}-syncbrain"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncbrain
  template:
    metadata:
      labels:
        app: syncbrain
    spec:
      containers:
        - name: syncbrain
          image: "{{ .Values.syncbrain.image }}"
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              value: "{{ .Values.openaiApiKey }}"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
