apiVersion: v1
kind: Service
metadata:
  name: "{{ include \"kiki-agent.fullname\" . }}-syncflow"
spec:
  type: ClusterIP
  ports:
    - port: 8003
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: syncflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include \"kiki-agent.fullname\" . }}-syncflow"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncflow
  template:
    metadata:
      labels:
        app: syncflow
    spec:
      containers:
        - name: syncflow
          image: "{{ .Values.syncflow.image }}"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
