apiVersion: v1
kind: Service
metadata:
  name: "{{ include \"kiki-agent.fullname\" . }}-syncvalue"
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: syncvalue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include \"kiki-agent.fullname\" . }}-syncvalue"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncvalue
  template:
    metadata:
      labels:
        app: syncvalue
    spec:
      containers:
        - name: syncvalue
          image: "{{ .Values.syncvalue.image }}"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
