apiVersion: v1
kind: Service
metadata:
  name: "{{ include \"kiki-agent.fullname\" . }}-synccreate"
spec:
  type: ClusterIP
  ports:
    - port: 8004
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: synccreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include \"kiki-agent.fullname\" . }}-synccreate"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synccreate
  template:
    metadata:
      labels:
        app: synccreate
    spec:
      containers:
        - name: synccreate
          image: "{{ .Values.synccreate.image }}"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
