apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncshield-safefail.fullname" . }}
  labels:
    app: syncshield-safefail
spec:
  selector:
    app: syncshield-safefail
  ports:
    - name: rest
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50057
      targetPort: 50057
